#!/bin/bash

numlines=$1
tmp=$(mktemp /tmp/yjobs_lite.XXXXXX)
tmp2=$(mktemp /tmp/yjobs_lite.XXXXXX)

# get the basic bjobs output with number of running jobs and total jobs on top
(bjobs 2>&1) > $tmp
(bjobs -d 2>&1) > $tmp2

see_priority
numrunning=$(grep RUN $tmp | wc -l)
total=$(tail -n +2 $tmp | wc -l)
echo "$numrunning running, $total total"
head -$numlines $tmp
echo "===="
numexit=$(grep -v DONE $tmp2 | tail -n +2 | wc -l)
numdone=$(grep DONE $tmp2 | grep -v "No DONE" | wc -l)
echo "$numdone are done in past hour. $numexit terminated but not done"
cat $tmp2 | tail -$numlines

rm "$tmp"
rm "$tmp2"
