#!/bin/bash

# To get output of a non-interactive running job if there is one
# first, get id of top running job
JID=$(bjobs -w 2>&1 | grep RUN | grep -v interactive | tr -s " " | cut -d" " -f7 | head -1)

# now call bpeek on that job
if [ "$JID" == "" ]
then
    echo "no job found"
else
    echo "$JID"
    bjobs -w -J $JID
    echo "======="
    bpeek -J $JID
fi
